include: package:lint/strict.yaml

analyzer:
  exclude:
    - '**/**.g.dart'
    - '**/**.mapper.dart'
    - '**/generated/**'
    - '**/migration_test.dart'

linter:
  rules:
    # In some cases this is okay, e.g. when writing RenderObjects.
    avoid_setters_without_getters: false
    # https://github.com/passsy/dart-lint/issues/26
    unawaited_futures: true
    # https://github.com/passsy/dart-lint/issues/26
    # Has many false positives, but nevertheless makes the code much safer.
    discarded_futures: true
    # In some cases this is used to emphasize that a specific argument
    # value got chosen on purpose. Also, it makes code more readable in some
    # cases. E.g. Date(2021, 1, 1) vs Date(2021).
    avoid_redundant_argument_values: false

formatter:
  trailing_commas: preserve
